[profile.default]
solc_version = "0.8.17"
src = 'src'
out = 'out'
libs = ['lib']

#via_ir = true

#[optimized]
#fuzz_runs = 5000
#fuzz_max_global_rejects = 2_000_000
#optimizer_runs = 13_377
#out = 'optimized-out'
